name: CareGiving
favicon: null
layout_spectrum: 0.27808208926580846
typography_spectrum: 0.9780298676341772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9095014391932636
  lightness: 0.5562625015154481
  saturation: 0.6027881640475243
  rhythmicContrast: 0.3341895858757198
purpose: []
